default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: 'postgres'
  password: 'admin'

development:
  <<: *default
  database: object_state_development

test:
  <<: *default
  database: object_state_test

production:
  <<: *default
  database: object_state_production
  username: ''
  password: ''
